[2025-07-05T19:48:37.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T19:48:37.785+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T19:48:33.437361+00:00 [queued]>
[2025-07-05T19:48:37.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T19:48:33.437361+00:00 [queued]>
[2025-07-05T19:48:37.790+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T19:48:37.800+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-05 19:48:33.437361+00:00
[2025-07-05T19:48:37.803+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T19:48:37.803+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1796) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T19:48:37.804+0000] {standard_task_runner.py:63} INFO - Started process 1932 to run task
[2025-07-05T19:48:37.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-05T19:48:33.437361+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpxld65xbq']
[2025-07-05T19:48:37.806+0000] {standard_task_runner.py:91} INFO - Job 189: Subtask extract
[2025-07-05T19:48:37.843+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T19:48:33.437361+00:00 [running]> on host 93b0937d74ff
[2025-07-05T19:48:37.896+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T19:48:33.437361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T19:48:33.437361+00:00'
[2025-07-05T19:48:37.897+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T19:48:38.617+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-05T19:48:38.618+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T19:48:38.619+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-05T19:48:38.621+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T19:48:39.335+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T19:48:39.341+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T19:48:39.341+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T19:48:39.347+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-05T19:48:33.437361+00:00, execution_date=20250705T194833, start_date=20250705T194837, end_date=20250705T194839
[2025-07-05T19:48:39.382+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T19:48:39.393+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-05T19:48:39.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
