[2025-07-05T15:57:15.539+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T15:57:15.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T15:57:04.491842+00:00 [queued]>
[2025-07-05T15:57:15.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T15:57:04.491842+00:00 [queued]>
[2025-07-05T15:57:15.557+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T15:57:15.565+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_load> on 2025-07-05 15:57:04.491842+00:00
[2025-07-05T15:57:15.568+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T15:57:15.569+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2465) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T15:57:15.570+0000] {standard_task_runner.py:63} INFO - Started process 2605 to run task
[2025-07-05T15:57:15.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'transform_and_load', 'manual__2025-07-05T15:57:04.491842+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpsmy4jiy3']
[2025-07-05T15:57:15.573+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask transform_and_load
[2025-07-05T15:57:15.604+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T15:57:04.491842+00:00 [running]> on host 93b0937d74ff
[2025-07-05T15:57:15.655+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T15:57:04.491842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T15:57:04.491842+00:00'
[2025-07-05T15:57:15.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T15:57:16.549+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T15:57:16.550+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 125, in transform_and_load
    df = df.select([col(c).alias(c.lower()) for c in df.columns])
                    ^^^
NameError: name 'col' is not defined
[2025-07-05T15:57:16.556+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=practice_etl_pipeline, task_id=transform_and_load, run_id=manual__2025-07-05T15:57:04.491842+00:00, execution_date=20250705T155704, start_date=20250705T155715, end_date=20250705T155716
[2025-07-05T15:57:16.564+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task transform_and_load (name 'col' is not defined; 2605)
[2025-07-05T15:57:16.586+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T15:57:16.594+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T15:57:16.597+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
