[2025-07-05T15:57:09.582+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T15:57:09.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T15:57:04.491842+00:00 [queued]>
[2025-07-05T15:57:09.599+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T15:57:04.491842+00:00 [queued]>
[2025-07-05T15:57:09.600+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T15:57:09.609+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-05 15:57:04.491842+00:00
[2025-07-05T15:57:09.612+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T15:57:09.612+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T15:57:09.613+0000] {standard_task_runner.py:63} INFO - Started process 2430 to run task
[2025-07-05T15:57:09.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-05T15:57:04.491842+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9mteozrq']
[2025-07-05T15:57:09.616+0000] {standard_task_runner.py:91} INFO - Job 173: Subtask extract
[2025-07-05T15:57:09.652+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T15:57:04.491842+00:00 [running]> on host 93b0937d74ff
[2025-07-05T15:57:09.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T15:57:04.491842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T15:57:04.491842+00:00'
[2025-07-05T15:57:09.700+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T15:57:10.470+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-05T15:57:10.471+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T15:57:10.472+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-05T15:57:10.474+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T15:57:11.066+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T15:57:11.072+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T15:57:11.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T15:57:11.078+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-05T15:57:04.491842+00:00, execution_date=20250705T155704, start_date=20250705T155709, end_date=20250705T155711
[2025-07-05T15:57:11.110+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T15:57:11.121+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-05T15:57:11.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
