[2025-07-06T13:02:08.490+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T13:02:08.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:02:04.043782+00:00 [queued]>
[2025-07-06T13:02:08.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:02:04.043782+00:00 [queued]>
[2025-07-06T13:02:08.506+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-06T13:02:08.514+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-06 13:02:04.043782+00:00
[2025-07-06T13:02:08.517+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:02:08.518+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4240) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T13:02:08.519+0000] {standard_task_runner.py:63} INFO - Started process 4384 to run task
[2025-07-06T13:02:08.520+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-06T13:02:04.043782+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpebn8tulb']
[2025-07-06T13:02:08.522+0000] {standard_task_runner.py:91} INFO - Job 271: Subtask extract
[2025-07-06T13:02:08.557+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:02:04.043782+00:00 [running]> on host 93b0937d74ff
[2025-07-06T13:02:08.610+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T13:02:04.043782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T13:02:04.043782+00:00'
[2025-07-06T13:02:08.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T13:02:09.320+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-06T13:02:09.321+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:02:09.321+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-06T13:02:09.323+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:02:09.990+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-06|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-06T13:02:09.998+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-06T13:02:09.999+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T13:02:10.005+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-06T13:02:04.043782+00:00, execution_date=20250706T130204, start_date=20250706T130208, end_date=20250706T130210
[2025-07-06T13:02:10.016+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-06T13:02:10.027+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-06T13:02:10.029+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
