[2025-07-05T21:59:34.183+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T21:59:34.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:59:22.715278+00:00 [queued]>
[2025-07-05T21:59:34.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:59:22.715278+00:00 [queued]>
[2025-07-05T21:59:34.197+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T21:59:34.205+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_load> on 2025-07-05 21:59:22.715278+00:00
[2025-07-05T21:59:34.208+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T21:59:34.209+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T21:59:34.209+0000] {standard_task_runner.py:63} INFO - Started process 2639 to run task
[2025-07-05T21:59:34.211+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'transform_and_load', 'manual__2025-07-05T21:59:22.715278+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpryjwsc6j']
[2025-07-05T21:59:34.213+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask transform_and_load
[2025-07-05T21:59:34.248+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:59:22.715278+00:00 [running]> on host 93b0937d74ff
[2025-07-05T21:59:34.297+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T21:59:22.715278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T21:59:22.715278+00:00'
[2025-07-05T21:59:34.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T21:59:34.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T21:59:34.464+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 214, in transform_and_load
    df = convert_date_columns(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 143, in convert_date_columns
    df = df.withColumn(col_name, to_date(col(col_name), coalesce(*[to_date(col(col_name), frmt) for frmt in input_formats])))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/utils.py", line 282, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/functions/builtin.py", line 11340, in to_date
    return _invoke_function("to_date", _to_java_column(col), _enum_to_value(format))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/functions/builtin.py", line 107, in _invoke_function
    return Column(jf(*args))
                  ^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1354, in __call__
    args_command, temp_args = self._build_args(*args)
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1317, in _build_args
    (new_args, temp_args) = self._get_args(args)
                            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1304, in _get_args
    temp_arg = converter.convert(arg, self.gateway_client)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_collections.py", line 510, in convert
    for element in object:
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/classic/column.py", line 417, in __iter__
    raise PySparkTypeError(
pyspark.errors.exceptions.base.PySparkTypeError: [NOT_ITERABLE] Column is not iterable.
[2025-07-05T21:59:34.474+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=practice_etl_pipeline, task_id=transform_and_load, run_id=manual__2025-07-05T21:59:22.715278+00:00, execution_date=20250705T215922, start_date=20250705T215934, end_date=20250705T215934
[2025-07-05T21:59:34.481+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 257 for task transform_and_load ([NOT_ITERABLE] Column is not iterable.; 2639)
[2025-07-05T21:59:34.503+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T21:59:34.512+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T21:59:34.514+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
