[2025-07-05T14:08:44.565+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T14:08:44.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T14:08:40.288959+00:00 [queued]>
[2025-07-05T14:08:44.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T14:08:40.288959+00:00 [queued]>
[2025-07-05T14:08:44.581+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T14:08:44.588+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-05 14:08:40.288959+00:00
[2025-07-05T14:08:44.592+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T14:08:44.592+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=11379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T14:08:44.593+0000] {standard_task_runner.py:63} INFO - Started process 11601 to run task
[2025-07-05T14:08:44.595+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-05T14:08:40.288959+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp47c03a6z']
[2025-07-05T14:08:44.597+0000] {standard_task_runner.py:91} INFO - Job 136: Subtask extract
[2025-07-05T14:08:44.634+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T14:08:40.288959+00:00 [running]> on host 93b0937d74ff
[2025-07-05T14:08:44.683+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T14:08:40.288959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T14:08:40.288959+00:00'
[2025-07-05T14:08:44.683+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T14:08:44.861+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-05T14:08:44.862+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T14:08:44.862+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-05T14:08:44.864+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T14:08:45.279+0000] {logging_mixin.py:188} INFO - Текущий каталог: spark_catalog
[2025-07-05T14:08:46.166+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T14:08:46.307+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T14:08:46.309+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T14:08:46.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T14:08:46.315+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-05T14:08:40.288959+00:00, execution_date=20250705T140840, start_date=20250705T140844, end_date=20250705T140846
[2025-07-05T14:08:46.331+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T14:08:46.345+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-05T14:08:46.347+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
