[2025-07-06T21:58:35.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T21:58:35.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:57:52.780306+00:00 [queued]>
[2025-07-06T21:58:35.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:57:52.780306+00:00 [queued]>
[2025-07-06T21:58:35.338+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-06T21:58:35.346+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_log_data> on 2025-07-06 21:57:52.780306+00:00
[2025-07-06T21:58:35.349+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:58:35.350+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4435) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T21:58:35.351+0000] {standard_task_runner.py:63} INFO - Started process 4567 to run task
[2025-07-06T21:58:35.352+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'load_log_data', 'manual__2025-07-06T21:57:52.780306+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpmjtj62h_']
[2025-07-06T21:58:35.353+0000] {standard_task_runner.py:91} INFO - Job 317: Subtask load_log_data
[2025-07-06T21:58:35.356+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-06T21:58:35.357+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:58:35.358+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-06T21:58:35.360+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:58:35.388+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:57:52.780306+00:00 [running]> on host 93b0937d74ff
[2025-07-06T21:58:35.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_log_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T21:57:52.780306+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T21:57:52.780306+00:00'
[2025-07-06T21:58:35.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T21:58:40.165+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-06T21:58:40.165+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T21:58:40.171+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=load_log_data, run_id=manual__2025-07-06T21:57:52.780306+00:00, execution_date=20250706T215752, start_date=20250706T215835, end_date=20250706T215840
[2025-07-06T21:58:40.217+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-06T21:58:40.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T21:58:40.230+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
