[2025-07-05T12:20:16.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T12:20:16.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T12:20:08.540066+00:00 [queued]>
[2025-07-05T12:20:16.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T12:20:08.540066+00:00 [queued]>
[2025-07-05T12:20:16.719+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T12:20:16.727+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_load> on 2025-07-05 12:20:08.540066+00:00
[2025-07-05T12:20:16.730+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T12:20:16.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T12:20:16.732+0000] {standard_task_runner.py:63} INFO - Started process 457 to run task
[2025-07-05T12:20:16.733+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'transform_and_load', 'manual__2025-07-05T12:20:08.540066+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8jwv6kzk']
[2025-07-05T12:20:16.735+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask transform_and_load
[2025-07-05T12:20:16.772+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T12:20:08.540066+00:00 [running]> on host 6802b12b52ea
[2025-07-05T12:20:16.819+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T12:20:08.540066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T12:20:08.540066+00:00'
[2025-07-05T12:20:16.820+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T12:20:17.188+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-05T12:20:17.189+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T12:20:17.189+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-05T12:20:17.191+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T12:20:20.004+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T12:20:20.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T12:20:20.009+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=transform_and_load, run_id=manual__2025-07-05T12:20:08.540066+00:00, execution_date=20250705T122008, start_date=20250705T122016, end_date=20250705T122020
[2025-07-05T12:20:20.034+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T12:20:20.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
