[2025-07-05T13:32:14.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T13:32:14.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T13:32:10.107292+00:00 [queued]>
[2025-07-05T13:32:14.309+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T13:32:10.107292+00:00 [queued]>
[2025-07-05T13:32:14.309+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T13:32:14.318+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-05 13:32:10.107292+00:00
[2025-07-05T13:32:14.321+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T13:32:14.321+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5614) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T13:32:14.322+0000] {standard_task_runner.py:63} INFO - Started process 5746 to run task
[2025-07-05T13:32:14.324+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-05T13:32:10.107292+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpf47u54ys']
[2025-07-05T13:32:14.325+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask extract
[2025-07-05T13:32:14.359+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T13:32:10.107292+00:00 [running]> on host 93b0937d74ff
[2025-07-05T13:32:14.405+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T13:32:10.107292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T13:32:10.107292+00:00'
[2025-07-05T13:32:14.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T13:32:14.413+0000] {logging_mixin.py:188} INFO - {'url': 'jdbc:postgresql://88.218.77.95:5432/postgres', 'user': 'wadss', 'password': 'Reza4ok3141', 'driver': 'org.postgresql.Driver'}
[2025-07-05T13:32:14.863+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-05T13:32:14.864+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T13:32:14.865+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-05T13:32:14.867+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T13:32:15.754+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T13:32:15.883+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-05|ИНФО  |файлы обработаны и переданы в загрузку|6      |
+----------+------+--------------------------------------+-------+
[2025-07-05T13:32:15.887+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T13:32:15.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T13:32:15.893+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-05T13:32:10.107292+00:00, execution_date=20250705T133210, start_date=20250705T133214, end_date=20250705T133215
[2025-07-05T13:32:15.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T13:32:15.953+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-05T13:32:15.956+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
