[2025-07-06T13:29:04.105+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T13:29:04.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:28:59.227723+00:00 [queued]>
[2025-07-06T13:29:04.120+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:28:59.227723+00:00 [queued]>
[2025-07-06T13:29:04.121+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-06T13:29:04.129+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-06 13:28:59.227723+00:00
[2025-07-06T13:29:04.133+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:29:04.133+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9220) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T13:29:04.134+0000] {standard_task_runner.py:63} INFO - Started process 9358 to run task
[2025-07-06T13:29:04.136+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-06T13:28:59.227723+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpjlggq6uj']
[2025-07-06T13:29:04.137+0000] {standard_task_runner.py:91} INFO - Job 289: Subtask extract
[2025-07-06T13:29:04.170+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-06T13:28:59.227723+00:00 [running]> on host 93b0937d74ff
[2025-07-06T13:29:04.223+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T13:28:59.227723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T13:28:59.227723+00:00'
[2025-07-06T13:29:04.224+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T13:29:04.267+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-06T13:29:04.268+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:29:04.268+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-06T13:29:04.270+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T13:29:05.554+0000] {logging_mixin.py:188} INFO - +----------+------+--------------------------------------+-------+
|timestamp |status|message                               |obj_num|
+----------+------+--------------------------------------+-------+
|2025-07-06|ИНФО  |файлы обработаны и переданы в загрузку|1      |
+----------+------+--------------------------------------+-------+
[2025-07-06T13:29:05.564+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-06T13:29:05.564+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T13:29:05.570+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-06T13:28:59.227723+00:00, execution_date=20250706T132859, start_date=20250706T132904, end_date=20250706T132905
[2025-07-06T13:29:05.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-06T13:29:05.602+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-06T13:29:05.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
