[2025-07-06T21:46:28.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T21:46:28.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:45:45.310719+00:00 [queued]>
[2025-07-06T21:46:28.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:45:45.310719+00:00 [queued]>
[2025-07-06T21:46:28.857+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-06T21:46:28.865+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_log_data> on 2025-07-06 21:45:45.310719+00:00
[2025-07-06T21:46:28.869+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:46:28.869+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2574) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T21:46:28.870+0000] {standard_task_runner.py:63} INFO - Started process 2708 to run task
[2025-07-06T21:46:28.872+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'load_log_data', 'manual__2025-07-06T21:45:45.310719+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpy6lq9iyz']
[2025-07-06T21:46:28.873+0000] {standard_task_runner.py:91} INFO - Job 311: Subtask load_log_data
[2025-07-06T21:46:28.877+0000] {clientserver.py:529} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-07-06T21:46:28.878+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:46:28.878+0000] {java_gateway.py:1056} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 527, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/clientserver.py", line 530, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-07-06T21:46:28.880+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-06T21:46:28.906+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.load_log_data manual__2025-07-06T21:45:45.310719+00:00 [running]> on host 93b0937d74ff
[2025-07-06T21:46:28.955+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_log_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T21:45:45.310719+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T21:45:45.310719+00:00'
[2025-07-06T21:46:28.956+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T21:46:33.755+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-06T21:46:33.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T21:46:33.761+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=load_log_data, run_id=manual__2025-07-06T21:45:45.310719+00:00, execution_date=20250706T214545, start_date=20250706T214628, end_date=20250706T214633
[2025-07-06T21:46:33.777+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-06T21:46:33.786+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T21:46:33.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
